import jsPDF from 'jspdf';
import type { AgentResponse, ContractResult, Grade } from '../types';
import { calculateGrade, MAXEX_FIELDS, fieldStatus } from './grading';

// ── Color palette ─────────────────────────────────────────────────────────────

type RGB = [number, number, number];

const C: Record<string, RGB> = {
  navy:      [17,  56,  95],
  white:     [255, 255, 255],
  s800:      [30,  41,  59],
  s500:      [100, 116, 139],
  s200:      [226, 232, 240],
  red700:    [185, 28,  28],
  amb700:    [180, 83,  9],
  grn700:    [4,   120, 87],
  emBg:      [209, 250, 229],
  yelBg:     [254, 243, 199],
  ornBg:     [255, 237, 213],
  redBg:     [254, 226, 226],
  redCellBg: [254, 242, 242],
  redBord:   [252, 165, 165],
  ambBg:     [255, 251, 235],
  ambBord:   [253, 211, 77],
  grnBg:     [236, 253, 245],
  grnBord:   [167, 243, 208],
  barGrn:    [16,  185, 129],
  barYel:    [245, 158, 11],
  barRed:    [239, 68,  68],
};

const GRADE_FG: Record<Grade, string> = { A: 'grn700', B: 'grn700', C: 'amb700', D: 'red700', F: 'red700' };
const GRADE_BG: Record<Grade, string> = { A: 'emBg',   B: 'emBg',   C: 'yelBg', D: 'ornBg',  F: 'redBg'  };

function fc(doc: jsPDF, k: string) { const [r,g,b] = C[k]; doc.setFillColor(r,g,b); }
function sc(doc: jsPDF, k: string) { const [r,g,b] = C[k]; doc.setDrawColor(r,g,b); }
function tc(doc: jsPDF, k: string) { const [r,g,b] = C[k]; doc.setTextColor(r,g,b); }

// ── Page constants ────────────────────────────────────────────────────────────

const PW = 215.9; // letter width mm
const PH = 279.4; // letter height mm
const M  = 18;    // margin
const CW = PW - 2*M;

// ── Shared header / footer ────────────────────────────────────────────────────

function drawPageHeader(doc: jsPDF, title: string, date: string) {
  fc(doc, 'navy');
  doc.rect(0, 0, PW, 28, 'F');
  tc(doc, 'white');
  doc.setFont('helvetica', 'bold');   doc.setFontSize(16); doc.text('MAXEX', M, 12);
  doc.setFont('helvetica', 'normal'); doc.setFontSize(9);  doc.text('Mortgage Schema Validator', M, 18);
  doc.setFont('helvetica', 'bold');   doc.setFontSize(10); doc.text(title, PW-M, 12, { align: 'right' });
  doc.setFont('helvetica', 'normal'); doc.setFontSize(8);  doc.text(date,  PW-M, 18, { align: 'right' });
}

function drawPageFooter(doc: jsPDF) {
  fc(doc, 'navy');
  doc.rect(0, PH-12, PW, 12, 'F');
  tc(doc, 'white');
  doc.setFont('helvetica', 'normal'); doc.setFontSize(7);
  doc.text('Generated by MAXEX Mortgage Schema Validator', PW/2, PH-4.5, { align: 'center' });
}

function applyFooters(doc: jsPDF) {
  const total = doc.getNumberOfPages();
  for (let p = 1; p <= total; p++) {
    doc.setPage(p);
    drawPageFooter(doc);
  }
}

// ── Validation Report PDF ─────────────────────────────────────────────────────

export function downloadValidationReport(response: AgentResponse): void {
  const doc = new jsPDF('portrait', 'mm', 'letter');
  const { validation } = response;
  const { grade, score } = calculateGrade(validation);
  const date = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });

  drawPageHeader(doc, 'Validation Report', date);
  let y = 36;

  // Loan ID
  tc(doc, 's500'); doc.setFont('helvetica', 'normal'); doc.setFontSize(8); doc.text('LOAN ID', M, y);
  tc(doc, 's800'); doc.setFont('helvetica', 'bold');   doc.setFontSize(11);
  doc.text(validation.loan_id ?? response.loan_id ?? 'N/A', M, y+5);
  y += 16;

  // Grade block
  fc(doc, GRADE_BG[grade]);
  doc.roundedRect(M, y, 50, 30, 3, 3, 'F');
  tc(doc, GRADE_FG[grade]);
  doc.setFont('helvetica', 'bold'); doc.setFontSize(36);
  doc.text(grade, M+10, y+22);

  tc(doc, 's800');
  doc.setFontSize(11);
  doc.text(validation.is_valid ? 'Loan Approved' : 'Loan Rejected', M+56, y+10);
  tc(doc, 's500');
  doc.setFont('helvetica', 'normal'); doc.setFontSize(9);
  doc.text(`Quality Score: ${score}/100`, M+56, y+17);

  // Score bar
  const barX = M+56, barY = y+21, barW = CW-58;
  fc(doc, 's200'); doc.roundedRect(barX, barY, barW, 4, 2, 2, 'F');
  const barKey = (grade === 'A' || grade === 'B') ? 'barGrn' : grade === 'C' ? 'barYel' : 'barRed';
  fc(doc, barKey); doc.roundedRect(barX, barY, barW * score / 100, 4, 2, 2, 'F');
  y += 42;

  // Field results grid
  tc(doc, 's800'); doc.setFont('helvetica', 'bold'); doc.setFontSize(8.5);
  doc.text('FIELD RESULTS', M, y); y += 5;

  const cols = 3, cellW = CW/cols, cellH = 7;
  MAXEX_FIELDS.forEach((field, i) => {
    const st = fieldStatus(field, validation.violations, validation.warnings);
    const col = i % cols, row = Math.floor(i / cols);
    const cx = M + col*cellW, cy = y + row*(cellH+1.5);
    const [bgK, bdK, txK] =
      st === 'violation' ? ['redCellBg', 'redBord', 'red700'] :
      st === 'warning'   ? ['ambBg',     'ambBord', 'amb700'] :
                           ['grnBg',     'grnBord', 'grn700'];
    fc(doc, bgK); sc(doc, bdK);
    doc.roundedRect(cx, cy, cellW-1.5, cellH, 1.5, 1.5, 'FD');
    tc(doc, txK); doc.setFont('helvetica', 'normal'); doc.setFontSize(7);
    doc.text(field, cx+3, cy+4.5);
    const sym = st === 'violation' ? 'X' : st === 'warning' ? '!' : 'OK';
    doc.text(sym, cx+cellW-5, cy+4.5, { align: 'right' });
  });
  y += Math.ceil(MAXEX_FIELDS.length / cols) * (cellH+1.5) + 6;

  // Violations
  if (validation.violations.length > 0) {
    tc(doc, 'red700'); doc.setFont('helvetica', 'bold'); doc.setFontSize(8.5);
    doc.text(`VIOLATIONS (${validation.violations.length})`, M, y); y += 5;
    for (const v of validation.violations) {
      const lines = doc.splitTextToSize(`X  ${v}`, CW-8) as string[];
      const bh = lines.length * 4.5 + 4;
      fc(doc, 'redCellBg'); sc(doc, 'redBord');
      doc.roundedRect(M, y, CW, bh, 1.5, 1.5, 'FD');
      tc(doc, 'red700'); doc.setFont('helvetica', 'normal'); doc.setFontSize(7.5);
      for (let li = 0; li < lines.length; li++) doc.text(lines[li], M+4, y+4+li*4.5);
      y += bh + 2;
    }
    y += 3;
  }

  // Warnings
  if (validation.warnings.length > 0) {
    tc(doc, 'amb700'); doc.setFont('helvetica', 'bold'); doc.setFontSize(8.5);
    doc.text(`WARNINGS (${validation.warnings.length})`, M, y); y += 5;
    for (const w of validation.warnings) {
      const lines = doc.splitTextToSize(`!  ${w}`, CW-8) as string[];
      const bh = lines.length * 4.5 + 4;
      fc(doc, 'ambBg'); sc(doc, 'ambBord');
      doc.roundedRect(M, y, CW, bh, 1.5, 1.5, 'FD');
      tc(doc, 'amb700'); doc.setFont('helvetica', 'normal'); doc.setFontSize(7.5);
      for (let li = 0; li < lines.length; li++) doc.text(lines[li], M+4, y+4+li*4.5);
      y += bh + 2;
    }
  }

  if (validation.violations.length === 0 && validation.warnings.length === 0) {
    fc(doc, 'grnBg'); sc(doc, 'grnBord');
    doc.roundedRect(M, y, CW, 10, 2, 2, 'FD');
    tc(doc, 'grn700'); doc.setFont('helvetica', 'normal'); doc.setFontSize(8);
    doc.text('All MAXEX schema rules passed with no warnings.', M+4, y+6.5);
  }

  applyFooters(doc);
  doc.save(`maxex-report-${validation.loan_id ?? response.loan_id ?? 'unknown'}.pdf`);
}

// ── Contract PDF ──────────────────────────────────────────────────────────────

export function downloadContractPDF(contract: ContractResult): void {
  const doc = new jsPDF('portrait', 'mm', 'letter');
  const date = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });

  drawPageHeader(doc, 'Purchase Contract', date);
  let y = 36;

  // Loan ID + version
  tc(doc, 's500'); doc.setFont('helvetica', 'normal'); doc.setFontSize(8);
  doc.text('LOAN ID', M, y); doc.text('VERSION', M+80, y);
  tc(doc, 's800'); doc.setFont('helvetica', 'bold'); doc.setFontSize(11);
  doc.text(contract.loan_id, M, y+5); doc.text(contract.contract_version, M+80, y+5);
  y += 18;

  sc(doc, 's200'); doc.line(M, y, PW-M, y); y += 8;

  // Contract body — render line by line, add pages as needed
  const BOTTOM = PH - 18;
  for (const raw of contract.contract_text.split('\n')) {
    const trimmed = raw.trim();
    if (!trimmed) { y += 3; continue; }

    const isHdr = /^[A-Z][A-Z\s]{4,}$/.test(trimmed) || /^\d+[\.\)]\s/.test(trimmed);
    doc.setFont('helvetica', isHdr ? 'bold' : 'normal');
    doc.setFontSize(isHdr ? 9 : 8.5);
    tc(doc, 's800');

    const wrapped = doc.splitTextToSize(trimmed, CW) as string[];
    const lh = isHdr ? 5.5 : 4.5;
    if (isHdr) y += 3;

    for (const line of wrapped) {
      if (y + lh > BOTTOM) {
        doc.addPage();
        // small page marker
        tc(doc, 's500'); doc.setFont('helvetica', 'normal'); doc.setFontSize(7);
        doc.text(`MAXEX Mortgage Schema Validator  —  ${contract.loan_id}`, M, 10);
        tc(doc, 's800'); doc.setFont('helvetica', isHdr ? 'bold' : 'normal'); doc.setFontSize(isHdr ? 9 : 8.5);
        y = 18;
      }
      doc.text(line, M, y); y += lh;
    }
    y += isHdr ? 3 : 1.5;
  }

  // Signature block
  const sigH = 52;
  if (y + sigH > BOTTOM) { doc.addPage(); y = 20; } else { y += 10; }

  sc(doc, 's200'); doc.line(M, y, PW-M, y); y += 8;
  tc(doc, 's800'); doc.setFont('helvetica', 'bold'); doc.setFontSize(9);
  doc.text('SIGNATURES', M, y); y += 10;

  const sw = 75, dw = 35, dx = M + sw + 10;
  sc(doc, 's500');
  doc.line(M, y+8, M+sw, y+8); doc.line(dx, y+8, dx+dw, y+8);
  tc(doc, 's500'); doc.setFont('helvetica', 'normal'); doc.setFontSize(7.5);
  doc.text('Borrower Signature', M, y+12); doc.text('Date', dx, y+12);
  y += 22;
  doc.line(M, y+8, M+sw, y+8); doc.line(dx, y+8, dx+dw, y+8);
  doc.text('Lender / Servicer Signature', M, y+12); doc.text('Date', dx, y+12);

  applyFooters(doc);
  doc.save(`contract-${contract.loan_id}.pdf`);
}
